# Generated by Django 5.0.3 on 2024-03-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eightVue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eightballresponse',
            name='classifier',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
